CC      ?= cc
CFLAGS  ?= -O2 -Wall -Wextra
ENGINE  ?= ../moe-stream/c

all: tracker maintainer liblumabri.so test_shim lumabri

lumabri: lumabri.c lumabri_proto.h lumabri_sign.h
	$(CC) $(CFLAGS) -pthread lumabri.c -o $@

# ---- phase 2: peers execute experts ------------------------------------
# Both sides are built from the engine's own source so the expert math cannot
# drift between local and remote: expert_node.c includes olmoe.c, and the
# chatter is olmoe.c itself with -DLUMABRI_P2P.
P2P_CFLAGS = -O2 -fopenmp -Wall -I. -I$(ENGINE) \
             -Wno-unused-function -Wno-unused-parameter

phase2: expert_node olmoe_p2p
phase2-glm: expert_node_glm

# Which engines this colibri checkout actually has. deepseek.c in particular
# is GENERATED by colibri's tools/amalgamate_deepseek.py and is NOT in a fresh
# clone, so requiring it unconditionally breaks the build for everyone who has
# not run that generator — including anyone who only wants GLM. Everything is
# per engine anyway, so build what is there and say what was skipped.
HAVE_ENGINES := $(notdir $(basename $(wildcard $(ENGINE)/olmoe.c $(ENGINE)/colibri.c \
                 $(ENGINE)/inkling.c $(ENGINE)/kimi_k3.c $(ENGINE)/deepseek.c)))
NODE_olmoe    = expert_node
NODE_colibri  = expert_node_glm
NODE_inkling  = expert_node_inkling
NODE_kimi_k3  = expert_node_kimi
NODE_deepseek = expert_node_deepseek

ENGINE_NODES    = $(foreach e,$(HAVE_ENGINES),$(NODE_$(e)))
ENGINE_CHATTERS = $(foreach e,$(HAVE_ENGINES),$(e)_p2p)
MISSING_ENGINES = $(filter-out $(HAVE_ENGINES),olmoe colibri inkling kimi_k3 deepseek)

# A strict distributed run must not mix engine sources or numeric build
# profiles. Hash contents only (not absolute paths), then inject the same ID
# into the chatter and expert-node build for that family. Compiler/ISA/OpenMP
# details are appended at runtime by lmb_build_profile().
ENGINE_PROFILE_DEPS := $(sort $(wildcard $(ENGINE)/*.h)) \
                       lumabri_client.h lumabri_proto.h lumabri_sign.h lumabri_sha.h
define engine_source_id
$(shell sha256sum $(ENGINE)/$(1).c $(ENGINE_PROFILE_DEPS) \
        expert_engines/$(2).h engine_patches/$(1)-p2p.diff 2>/dev/null | \
        awk '{print $$1}' | sha256sum | cut -c1-16)
endef
SRCID_olmoe   := $(call engine_source_id,olmoe,olmoe)
SRCID_colibri := $(call engine_source_id,colibri,colibri)
SRCID_inkling := $(call engine_source_id,inkling,inkling)
SRCID_kimi_k3 := $(call engine_source_id,kimi_k3,kimi_k3)
SRCID_deepseek:= $(call engine_source_id,deepseek,deepseek)

PROFILE_olmoe   = -DLMBE_ENGINE_ID='"olmoe"'      -DLMBE_SOURCE_ID='"$(SRCID_olmoe)"'   -DLMBE_EXPECT_BITS=0
PROFILE_colibri = -DLMBE_ENGINE_ID='"colibri"'    -DLMBE_SOURCE_ID='"$(SRCID_colibri)"' -DLMBE_EXPECT_BITS=8
PROFILE_inkling = -DLMBE_ENGINE_ID='"inkling"'    -DLMBE_SOURCE_ID='"$(SRCID_inkling)"' -DLMBE_EXPECT_BITS=8
PROFILE_kimi_k3 = -DLMBE_ENGINE_ID='"kimi_k3"'    -DLMBE_SOURCE_ID='"$(SRCID_kimi_k3)"' -DLMBE_EXPECT_BITS=0
PROFILE_deepseek= -DLMBE_ENGINE_ID='"deepseek_v4"' -DLMBE_SOURCE_ID='"$(SRCID_deepseek)"' -DLMBE_EXPECT_BITS=0

# every engine's peer in one go — the ones this checkout has
engines: $(ENGINE_NODES)
	@$(if $(MISSING_ENGINES),echo "  skipped (not in $(ENGINE)): $(MISSING_ENGINES)";\
	   echo "  deepseek.c is generated by colibri's tools/amalgamate_deepseek.py",:)

# everything phase 2 needs, both sides
phase2-all: engines chatters

# One expert-node binary per engine. The body is the same file; everything
# engine-shaped lives in expert_engines/<name>.h, which pulls in the engine's
# own source so remote and local run the same kernels on the same weights.
EXPERT_DEPS = expert_node.c lumabri_proto.h lumabri_sign.h

expert_node: $(EXPERT_DEPS) expert_engines/olmoe.h $(ENGINE)/olmoe.c \
             engine_patches/olmoe-p2p.diff $(ENGINE_PROFILE_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_olmoe) expert_node.c -o $@ -lm -lpthread

expert_node_glm: $(EXPERT_DEPS) expert_engines/colibri.h $(ENGINE)/colibri.c \
                 engine_patches/colibri-p2p.diff $(ENGINE_PROFILE_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_colibri) -DLMBE_ENGINE_HEADER='"expert_engines/colibri.h"' \
	      expert_node.c -o $@ -lm -lpthread

expert_node_inkling: $(EXPERT_DEPS) expert_engines/inkling.h $(ENGINE)/inkling.c \
                     engine_patches/inkling-p2p.diff $(ENGINE_PROFILE_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_inkling) -DLMBE_ENGINE_HEADER='"expert_engines/inkling.h"' \
	      expert_node.c -o $@ -lm -lpthread

expert_node_kimi: $(EXPERT_DEPS) expert_engines/kimi_k3.h $(ENGINE)/kimi_k3.c \
                  engine_patches/kimi_k3-p2p.diff $(ENGINE_PROFILE_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_kimi_k3) -DLMBE_ENGINE_HEADER='"expert_engines/kimi_k3.h"' \
	      expert_node.c -o $@ -lm -lpthread

# DeepSeek V4 needs two extra things at build time.
#
# Its own -D set (upstream's expert-store sizing) has to match, or the store
# is laid out differently than the engine expects.
#
# And deepseek.c does `#undef main` halfway through — it renames a legacy
# entry point of its own — which kills the usual `#define main` trick every
# other glue relies on. So the CLI entry point is renamed textually into a
# build copy instead. One deterministic substitution, and if upstream ever
# changes that signature the copy still has a second main() and the compile
# says so rather than silently building the wrong program.
DS_CFLAGS = -DCOLI_V4_MAX_PIN_SLOTS_PER_LAYER=16 -DCOLI_V4_PIN_RAMP_REQUESTS=24 \
            -DCOLI_V4_EXPERIMENTAL_BLOCK_OTHER_PROFILE \
            -DCOLI_V4_EXPERIMENTAL_DUAL_EXPERT_LOADER

build/deepseek_noentry.c: $(ENGINE)/deepseek.c
	@mkdir -p build
	@sed 's/^int main(int argc, char \*\*argv) {/int deepseek_cli_main_unused(int argc, char **argv) {/' \
	     $< > $@
	@grep -q deepseek_cli_main_unused $@ || \
	  { echo "deepseek.c: main() signature changed — update the rule"; exit 1; }

expert_node_deepseek: $(EXPERT_DEPS) expert_engines/deepseek.h build/deepseek_noentry.c \
                      engine_patches/deepseek-p2p.diff $(ENGINE_PROFILE_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_deepseek) $(DS_CFLAGS) -Ibuild \
	      -DLMBE_ENGINE_HEADER='"expert_engines/deepseek.h"' \
	      expert_node.c -o $@ -lm -lpthread

# Regenerate the engine patches from a colibri checkout (never modifies it)
patches:
	python3 engine_patches/make_patches.py --engine-dir $(ENGINE)

patches-check:
	python3 engine_patches/make_patches.py --engine-dir $(ENGINE) --check

# ---- the chatter side: one patched engine binary per engine -------------
#
# `lumabri chat` prefers <engine>_p2p over <engine> in --engines-dir, and
# without one it runs the stock engine — which works, but phase 2 never
# engages and the chatter quietly downloads expert weights instead of asking
# peers to run them. So every engine needs its build here, not just olmoe.
#
# The engine is never modified: the patch is applied to a COPY under build/.
# A working copy that already has the patch applied is taken as-is, so an
# engine tree someone patched by hand still builds. Early OLMoE patches used
# `L.on` directly; normalize that old hook in the build copy so periodic
# discovery still runs while phase 2 is active.
#
# -DLUMIBRI_P2P: the patches predate the rename and test that macro; both
# spellings are defined so either vintage compiles.
build/%_p2p.c: $(ENGINE)/%.c engine_patches/%-p2p.diff Makefile
	@mkdir -p build
	@if grep -q LUMIBRI_P2P $<; then cp $< $@; \
	 else patch -s -p2 -o $@ $< engine_patches/$*-p2p.diff; fi
	@sed -i 's/if (L\.on) {/if (lumi_layer_on(layer)) {/' $@

ENGINE_P2P_DEPS = lumabri_client.h lumibri_client.h lumabri_proto.h lumabri_sign.h

olmoe_p2p: build/olmoe_p2p.c $(ENGINE_P2P_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_olmoe) -DLUMABRI_P2P -DLUMIBRI_P2P $< -o $@ -lm -lpthread

colibri_p2p: build/colibri_p2p.c $(ENGINE_P2P_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_colibri) -DLUMABRI_P2P -DLUMIBRI_P2P $< -o $@ -lm -lpthread

inkling_p2p: build/inkling_p2p.c $(ENGINE_P2P_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_inkling) -DLUMABRI_P2P -DLUMIBRI_P2P $< -o $@ -lm -lpthread

kimi_k3_p2p: build/kimi_k3_p2p.c $(ENGINE_P2P_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_kimi_k3) -DLUMABRI_P2P -DLUMIBRI_P2P $< -o $@ -lm -lpthread

deepseek_p2p: build/deepseek_p2p.c $(ENGINE_P2P_DEPS)
	$(CC) $(P2P_CFLAGS) $(PROFILE_deepseek) $(DS_CFLAGS) -DLUMABRI_P2P -DLUMIBRI_P2P $< -o $@ -lm -lpthread

# what a CHATTER needs; `engines` is what a compute DONOR needs
chatters: $(ENGINE_CHATTERS)

tiny_olmoe/config.json: make_tiny_olmoe.py
	python3 make_tiny_olmoe.py tiny_olmoe

fixture: tiny_olmoe/config.json

test-phase2: phase2 fixture
	./phase2_test.sh

test-phase2-glm: phase2-glm
	./phase2_glm_test.sh

test-phase2-inkling: expert_node_inkling
	./phase2_inkling_test.sh

test-phase2-kimi: expert_node_kimi
	./phase2_kimi_test.sh

# needs a real DeepSeek V4 model: MODEL=<dir> (no synthetic fixture, see the
# script's header for why)
test-phase2-deepseek: expert_node_deepseek
	./phase2_deepseek_test.sh

# Every engine's byte-identity proof, one after the other. DeepSeek V4 has no
# synthetic fixture (see phase2_deepseek_test.sh), so it runs only when a real
# model is there — and says so when it is not, rather than quietly passing on
# four engines while claiming five.
test-engines: test-phase2 test-phase2-glm test-phase2-inkling test-phase2-kimi
	@if [ -f "$${MODEL:-$$HOME/deepseek_v4}/config.json" ]; then \
	    $(MAKE) --no-print-directory test-phase2-deepseek; \
	else \
	    echo; echo "── DeepSeek V4 SKIPPED: no model at $${MODEL:-$$HOME/deepseek_v4}"; \
	    echo "   it has no synthetic fixture — MODEL=<dir> make test-engines"; \
	fi

tracker: tracker.c lumabri_proto.h lumabri_sha.h lumabri_sign.h
	$(CC) $(CFLAGS) -pthread tracker.c -o $@

maintainer: maintainer.c lumabri_proto.h lumabri_sha.h lumabri_sign.h
	$(CC) $(CFLAGS) -pthread maintainer.c -o $@

# The shim interposes libc symbols, so it must not itself be interposable
# state: -fPIC shared object, resolved via RTLD_NEXT at load time.
liblumabri.so: lumashim.c lumabri_proto.h lumabri_sha.h lumabri_sign.h
	$(CC) $(CFLAGS) -shared -fPIC -pthread lumashim.c -o $@ -ldl

test_shim: test_shim.c
	$(CC) $(CFLAGS) test_shim.c -o $@

test_relay_exec: test_relay_exec.c lumabri_proto.h
	$(CC) $(CFLAGS) -pthread test_relay_exec.c -o $@

test_key_rotation: test_key_rotation.c lumabri_sign.h
	$(CC) $(CFLAGS) -pthread test_key_rotation.c -o $@

test_hedge: test_hedge.c lumabri_client.h lumabri_proto.h lumabri_sign.h
	$(CC) $(CFLAGS) -pthread test_hedge.c -o $@

test-relay-exec: tracker expert_node test_relay_exec fixture
	./relay_exec_test.sh
	./peer_identity_test.sh

test-cas: tracker maintainer liblumabri.so test_shim
	./cas_test.sh

test-key-rotation: test_key_rotation
	./test_key_rotation

test-hedge: test_hedge
	./test_hedge

test: all test_key_rotation test_hedge
	./selftest.sh
	./donate_test.sh
	./signed_donor_test.sh
	./role_test.sh
	./security_test.sh
	./expert_input_test.sh
	./prefetch_policy_test.sh
	./cas_test.sh
	./relay_exec_test.sh
	./test_key_rotation
	./test_hedge

# ---- deploy -------------------------------------------------------------
# make install                    → /usr/local (needs sudo)
# make install PREFIX=$$HOME/.local  → per-user, no root
# Every binary lands in PREFIX/bin (they find each other via /proc/self/exe)
# and the shim in PREFIX/lib/lumabri. Phase-2 binaries are installed when
# they have been built (make phase2 ENGINE=...).
PREFIX ?= /usr/local

install: all
	install -d $(DESTDIR)$(PREFIX)/bin $(DESTDIR)$(PREFIX)/lib/lumabri
	install -m 755 lumabri tracker maintainer $(DESTDIR)$(PREFIX)/bin/
	install -m 644 liblumabri.so $(DESTDIR)$(PREFIX)/lib/lumabri/
	@for b in expert_node expert_node_glm expert_node_inkling expert_node_kimi \
	         expert_node_deepseek \
	         olmoe_p2p colibri_p2p inkling_p2p kimi_k3_p2p deepseek_p2p; do \
	    [ -f $$b ] && install -m 755 $$b $(DESTDIR)$(PREFIX)/bin/ || true; done
	@echo "installed under $(DESTDIR)$(PREFIX)"

clean:
	rm -f tracker maintainer liblumabri.so test_shim lumabri \
	      test_relay_exec test_key_rotation test_hedge \
	      olmoe_p2p colibri_p2p inkling_p2p kimi_k3_p2p deepseek_p2p \
	      expert_node expert_node_glm expert_node_inkling expert_node_kimi \
	      expert_node_deepseek
	rm -rf build

.PHONY: all test clean install phase2 phase2-glm engines chatters phase2-all \
        fixture test-phase2 \
        test-phase2-glm test-phase2-inkling test-phase2-kimi \
        test-phase2-deepseek test-engines \
        patches patches-check test-relay-exec test-cas test-key-rotation test-hedge
