"""Exercise resident loading with the native CI's small real adapter fixtures.

Fixtures are generated by Colibri, not downloaded production checkpoints.
The child home-flow gate owns and cleans up its own processes only.
"""
import argparse
import os
from pathlib import Path
import subprocess
import sys
import tempfile


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--fixtures", type=Path, required=True)
    parser.add_argument("--family", action="append", help="run only the named fixture families")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[2]
    cases = [
        ("olmoe", [], {}),
        ("qwen36", [], {}),
        ("inkling", [], {}),
        ("kimi", ["--donor-ram-gb", "4.5"], {}),
        ("glm", [], {}),
        ("glm53", [], {}),
        ("qwen38", ["--context", "512", "--expect-greedy"], {}),
        ("qwen38-fp8", ["--context", "512", "--expect-greedy"], {}),
        ("v4", ["--donor-ram-gb", "1.0"], {}),
    ]
    failures = []
    tested = []
    with tempfile.TemporaryDirectory(prefix="lumabri-resident-matrix-") as temporary:
        for name, extra, overrides in cases:
            if args.family and name not in args.family:
                continue
            tested.append(name)
            checkpoint = (args.fixtures / f"tiny-{name}-checkpoint").resolve(strict=True)
            if not (checkpoint / "config.json").is_file():
                raise RuntimeError(f"Missing fixture configuration: {checkpoint}")
            catalog = Path(temporary) / name
            catalog.mkdir()
            (catalog / f"tiny-{name}").symlink_to(checkpoint, target_is_directory=True)
            print(f"RESIDENT MATRIX: {name}", flush=True)
            result = subprocess.run(
                [sys.executable, str(root / "tests/integration/home_flow_test.py"),
                 "--models-dir", str(catalog), "--expect-metrics", "--resident-default", *extra],
                cwd=root, env={**os.environ, "LUMABRI_RESIDENT_REQUIRED": "1", **overrides},
                timeout=600, check=False)
            if result.returncode:
                failures.append(name)
    if failures:
        raise SystemExit("RESIDENT MATRIX FAILED: " + ", ".join(failures))
    if args.family and set(args.family) != set(tested):
        raise SystemExit("Unknown family requested")
    print("RESIDENT MATRIX PASS: " + ", ".join(tested) + "; weights retained across conversations")


if __name__ == "__main__":
    main()
